export const colorIcons = {
  black: require('./colors/black.svg'),
  gray: require('./colors/gray.svg'),
  silver: require('./colors/silver.svg'),
  white: require('./colors/white.svg'),
  blue: require('./colors/blue.svg'),
  violet: require('./colors/violet.svg'),
  pink: require('./colors/pink.svg'),
  red: require('./colors/red.svg'),
  vinous: require('./colors/vinous.svg'),
  brown: require('./colors/brown.svg'),
  beige: require('./colors/beige.svg'),
  gold: require('./colors/gold.svg'),
  orange: require('./colors/orange.svg'),
  yellow: require('./colors/yellow.svg'),
  green: require('./colors/green.svg'),
  another: require('./colors/another.svg'),
};
