export const brandList = [
  {
    value: '112',
    text: 'ВАЗ (Lada)',
    code: 'lada',
    popular: true,
  },
  {
    value: '14',
    text: 'Audi',
    code: 'audi',
    popular: true,
  },
  {
    value: '23',
    text: 'BMW',
    code: 'bmw',
    popular: true,
  },
  {
    value: '34',
    text: 'Cadillac',
    code: 'cadillac',
    popular: true,
  },
  // {
  //   value: '40',
  //   text: 'Chery',
  //   code: 'chery',
  //   popular: true,
  // },
  // {
  //   value: '41',
  //   text: 'Chevrolet',
  //   code: 'chevrolet',
  //   popular: true,
  // },
  // {
  //   value: '42',
  //   text: 'Chrysler',
  //   code: 'chrysler',
  //   popular: true,
  // },
  // {
  //   value: '43',
  //   text: 'Citroen',
  //   code: 'citroen',
  //   popular: true,
  // },
  // {
  //   value: '48',
  //   text: 'Daewoo',
  //   code: 'daewoo',
  //   popular: true,
  // },
  // {
  //   value: '57',
  //   text: 'Dodge',
  //   code: 'dodge',
  //   popular: true,
  // },
  // {
  //   value: '69',
  //   text: 'Fiat',
  //   code: 'fiat',
  //   popular: true,
  // },
  // {
  //   value: '71',
  //   text: 'Ford',
  //   code: 'ford',
  //   popular: true,
  // },
  // {
  //   value: '81',
  //   text: 'Great Wall',
  //   code: 'great-wall',
  //   popular: true,
  // },
  // {
  //   value: '88',
  //   text: 'Honda',
  //   code: 'honda',
  //   popular: true,
  // },
  // {
  //   value: '92',
  //   text: 'Hyundai',
  //   code: 'hyundai',
  //   popular: true,
  // },
  // {
  //   value: '94',
  //   text: 'Infiniti',
  //   code: 'infiniti',
  //   popular: true,
  // },
  // {
  //   value: '102',
  //   text: 'Jaguar',
  //   code: 'jaguar',
  //   popular: true,
  // },
  // {
  //   value: '103',
  //   text: 'Jeep',
  //   code: 'jeep',
  //   popular: true,
  // },
  // {
  //   value: '108',
  //   text: 'Kia',
  //   code: 'kia',
  //   popular: true,
  // },
  // {
  //   value: '115',
  //   text: 'Land Rover',
  //   code: 'land-rover',
  //   popular: true,
  // },
  // {
  //   value: '117',
  //   text: 'Lexus',
  //   code: 'lexus',
  //   popular: true,
  // },
  // {
  //   value: '119',
  //   text: 'Lifan',
  //   code: 'lifan',
  //   popular: true,
  // },
  // {
  //   value: '132',
  //   text: 'Mazda',
  //   code: 'mazda',
  //   popular: true,
  // },
  // {
  //   value: '135',
  //   text: 'Mercedes-Benz',
  //   code: 'mercedes',
  //   popular: true,
  // },
  // {
  //   value: '141',
  //   text: 'MINI',
  //   code: 'mini',
  //   popular: true,
  // },
  // {
  //   value: '142',
  //   text: 'Mitsubishi',
  //   code: 'mitsubishi',
  //   popular: true,
  // },
  // {
  //   value: '147',
  //   text: 'Nissan',
  //   code: 'nissan',
  //   popular: true,
  // },
  // {
  //   value: '150',
  //   text: 'Opel',
  //   code: 'opel',
  //   popular: true,
  // },
];

export const models = [
  {
    value: '16623',
    text: 'A1 II (GB)',
    code: 'a1_ii',
    start: '2018',
    end: '2019',
    model_group_id: '0',
  },
  {
    value: '16618',
    text: 'A3 III (8V) Рестайлинг',
    code: 'a3_iii(8v)-res',
    start: '2016',
    end: '2020',
    model_group_id: '0',
  },
  {
    value: '309',
    text: 'A4 allroad V (B9)',
    code: 'a4-allroad_v',
    start: '2015',
    end: '2019',
    model_group_id: '1',
  },
  {
    value: '17883',
    text: 'A4 allroad V (B9) Рестайлинг',
    code: 'a4_allroad_v_(b9)_res',
    start: '2019',
    end: '2021',
    model_group_id: '0',
  },
  {
    value: '307',
    text: 'A4 V (B9)',
    code: 'a4_v',
    start: '2015',
    end: '2019',
    model_group_id: '1',
  },
  {
    value: '17690',
    text: 'A4 V (B9) Рестайлинг',
    code: 'mod-553890',
    start: '2015',
    end: '2021',
    model_group_id: '0',
  },
  {
    value: '16396',
    text: 'A5 II (F5)',
    code: 'a5_2',
    start: '2016',
    end: '2019',
    model_group_id: '0',
  },
  {
    value: '17766',
    text: 'A5 II (F5) Рестайлинг',
    code: 'a5_ii-res',
    start: '2019',
    end: '2021',
    model_group_id: '0',
  },
  {
    value: '16444',
    text: 'A5 Sportback II',
    code: 'a5-sportback_ii',
    start: '2015',
    end: '2020',
    model_group_id: '0',
  },
  {
    value: '292',
    text: 'A6 allroad III (C7) Рестайлинг',
    code: 'a6-allroad_iii-res',
    start: '2014',
    end: '2019',
    model_group_id: '3',
  },
  {
    value: '17884',
    text: 'A6 allroad IV (C8)',
    code: 'allroad_iv_(c8)',
    start: '2019',
    end: '2021',
    model_group_id: '0',
  },
  {
    value: '16564',
    text: 'A6 V (C8)',
    code: 'a6_v_c8',
    start: '2015',
    end: '2021',
    model_group_id: '0',
  },
  {
    value: '16565',
    text: 'A7 II (4K)',
    code: 'a7_ii',
    start: '2018',
    end: '2021',
    model_group_id: '0',
  },
  {
    value: '16566',
    text: 'A8 IV (D5)',
    code: 'a8_ivd5',
    start: '2017',
    end: '2019',
    model_group_id: '0',
  },
  {
    value: '17636',
    text: 'A8L',
    code: 'a8l',
    start: '2004',
    end: '2020',
    model_group_id: '0',
  },
  {
    value: '16627',
    text: 'e-tron I',
    code: 'e_tron_i',
    start: '2018',
    end: '2020',
    model_group_id: '0',
  },
  {
    value: '205',
    text: 'Q2 I',
    code: 'q2_i',
    start: '2016',
    end: '2017',
    model_group_id: '0',
  },
  {
    value: '16567',
    text: 'Q3 II (F3)',
    code: 'q3_ii',
    start: '2018',
    end: '2021',
    model_group_id: '0',
  },
  {
    value: '17889',
    text: 'Q3 Sportback I (F3)',
    code: 'q3_sportback_i_(f3)',
    start: '2019',
    end: '2021',
    model_group_id: '0',
  },
  {
    value: '16301',
    text: 'Q5 II (FY)',
    code: 'q5_ii',
    start: '2017',
    end: '2020',
    model_group_id: '0',
  },
  {
    value: '256',
    text: 'Q7 II (4M)',
    code: 'q7_ii',
    start: '2015',
    end: '2019',
    model_group_id: '5',
  },
  {
    value: '17862',
    text: 'Q7 II (4M) Рестайлинг',
    code: 'q7_ii_res',
    start: '2019',
    end: '2021',
    model_group_id: '0',
  },
  {
    value: '16568',
    text: 'Q8 I',
    code: 'q8_i',
    start: '2018',
    end: '2021',
    model_group_id: '0',
  },
  {
    value: '17895',
    text: 'R8 II (4S) Рестайлинг',
    code: 'r8_ii_(4s)_res',
    start: '2019',
    end: '2021',
    model_group_id: '0',
  },
  {
    value: '16625',
    text: 'R8 II Рестайлинг',
    code: 'r8_ii-res',
    start: '2019',
    end: '2019',
    model_group_id: '0',
  },
  {
    value: '16300',
    text: 'RS 3 II (8V) Рестайлинг',
    code: 'rs3_ii-res',
    start: '2011',
    end: '2021',
    model_group_id: '0',
  },
  {
    value: '16619',
    text: 'RS 4 IV (B9)',
    code: 'rs4_iv(b9)',
    start: '2017',
    end: '2019',
    model_group_id: '0',
  },
  {
    value: '17897',
    text: 'RS 4 IV (B9) Рестайлинг',
    code: 'rs4_iv_(b9)_res',
    start: '2019',
    end: '2021',
    model_group_id: '0',
  },
  {
    value: '16318',
    text: 'RS 5 II (F5)',
    code: 'rs5_ii',
    start: '2010',
    end: '2021',
    model_group_id: '0',
  },
  {
    value: '17898',
    text: 'RS 5 II (F5) Рестайлинг',
    code: 'rs5_ii_(f5)_res',
    start: '2019',
    end: '2021',
    model_group_id: '0',
  },
  {
    value: '17899',
    text: 'RS 6 IV (C8)',
    code: 'rs6_iv_(c8)',
    start: '2019',
    end: '2021',
    model_group_id: '0',
  },
  {
    value: '17900',
    text: 'RS 7 II (4K)',
    code: 'rs7_ii_(4k)',
    start: '2019',
    end: '2021',
    model_group_id: '0',
  },
  {
    value: '228',
    text: 'RS Q3 I (8U) Рестайлинг',
    code: 'rs-q3_i-res',
    start: '2013',
    end: '2021',
    model_group_id: '0',
  },
  {
    value: '17902',
    text: 'RS Q3 II (F3)',
    code: 'rsq3_ii_(f3)',
    start: '2019',
    end: '2021',
    model_group_id: '0',
  },
  {
    value: '17903',
    text: 'RS Q3 Sportback I (F3)',
    code: 'rs_q3_sportback_i_(f3)',
    start: '2019',
    end: '2021',
    model_group_id: '0',
  },
  {
    value: '17904',
    text: 'RS Q8 I',
    code: 'rs_q8_i',
    start: '2019',
    end: '2021',
    model_group_id: '0',
  },
  {
    value: '16620',
    text: 'S3 III (8V) Рестайлинг',
    code: 's3_iii(8v)-res',
    start: '2016',
    end: '2019',
    model_group_id: '0',
  },
  {
    value: '308',
    text: 'S4 V (B9)',
    code: 's4_v',
    start: '2016',
    end: '2019',
    model_group_id: '0',
  },
  {
    value: '17906',
    text: 'S4 V (B9) Рестайлинг',
    code: 's4_v_(b9)',
    start: '2019',
    end: '2021',
    model_group_id: '0',
  },
  {
    value: '16621',
    text: 'S5 II (F5)',
    code: 's5_ii',
    start: '2016',
    end: '2019',
    model_group_id: '0',
  },
  {
    value: '17907',
    text: 'S5 II (F5) Рестайлинг',
    code: 's5_ii_(f5)_res',
    start: '2019',
    end: '2021',
    model_group_id: '0',
  },
  {
    value: '304',
    text: 'S6 IV (C7) Рестайлинг',
    code: 's6_iv-res',
    start: '2014',
    end: '2019',
    model_group_id: '0',
  },
  {
    value: '17908',
    text: 'S6 V (C8)',
    code: 's6_v_(c8)',
    start: '2019',
    end: '2021',
    model_group_id: '0',
  },
  {
    value: '17910',
    text: 'S7 II (4K)',
    code: 's7_ii_(4k)',
    start: '2019',
    end: '2021',
    model_group_id: '0',
  },
  {
    value: '17911',
    text: 'S8 IV (D5)',
    code: 's8_iv_(d5)',
    start: '2019',
    end: '2021',
    model_group_id: '0',
  },
  {
    value: '16626',
    text: 'SQ2 I',
    code: 'sq2_i',
    start: '2018',
    end: '2019',
    model_group_id: '0',
  },
  {
    value: '16319',
    text: 'SQ5 II (FY)',
    code: 'sq5_ii',
    start: '2017',
    end: '2017',
    model_group_id: '0',
  },
  {
    value: '206',
    text: 'SQ7 I (4M)',
    code: 'sq7_I',
    start: '2016',
    end: '2017',
    model_group_id: '0',
  },
  {
    value: '17915',
    text: 'SQ7 I (4M) Рестайлинг',
    code: 'sq7_i_(4m)_res',
    start: '2019',
    end: '2021',
    model_group_id: '0',
  },
  {
    value: '17799',
    text: 'SQ8 I (4M)',
    code: 'sq8_i_(4m)',
    start: '2019',
    end: '2021',
    model_group_id: '0',
  },
  {
    value: '273',
    text: 'TT III (8S)',
    code: 'tt_iii',
    start: '2014',
    end: '2019',
    model_group_id: '0',
  },
  {
    value: '16624',
    text: 'TT III (8S) Рестайлинг',
    code: 'tt_iii(8s)-res',
    start: '2018',
    end: '2019',
    model_group_id: '0',
  },
  {
    value: '16569',
    text: 'TT RS III (8S)',
    code: 'tt-rs_iii_8s',
    start: '2016',
    end: '2019',
    model_group_id: '0',
  },
  {
    value: '17916',
    text: 'TT RS III (8S) Рестайлинг',
    code: 'tt_rs_iii_(8s)_res',
    start: '2019',
    end: '2021',
    model_group_id: '0',
  },
  {
    value: '274',
    text: 'TTS III (8S)',
    code: 'tts_iii',
    start: '2014',
    end: '2019',
    model_group_id: '0',
  },
  {
    value: '17917',
    text: 'TTS III (8S) Рестайлинг',
    code: 'tts_iii_(8s)_res',
    start: '2018',
    end: '2021',
    model_group_id: '0',
  },
];
