export const internalIcons = {
  burgerOpen: require('./icons/burger-open.svg'),
  burgerClose: require('./icons/burger-close.svg'),
  arrow: require('./icons/arrow.svg'),
  region: require('./icons/region.svg'),
  phone: require('./icons/phone.svg'),
  enter: require('./icons/enter.svg'),
  vk: require('./icons/vk.svg'),
  facebook: require('./icons/facebook.svg'),
  ok: require('./icons/ok.svg'),
  instagram: require('./icons/instagram.svg'),
  youtube: require('./icons/youtube.svg'),
  cross: require('./icons/cross.svg'),
  yandex: require('./icons/yandex.svg'),
  google: require('./icons/google.svg'),
  otzovik: require('./icons/otzovik.svg'),
  arrowNext: require('./icons/arrow-next.svg'),
  arrowPrev: require('./icons/arrow-prev.svg'),
  arrowDown: require('./icons/arrow-down.svg'),
  starEmpty: require('./icons/star.svg'),
  starFull: require('./icons/star_full.svg'),
  checkOutline: require('./icons/check_outline.svg'),
} as const;
